[book]
authors = ["Beaumarchais"]
language = "fr"
multilingual = false
src = "src"
title = "La Folle Journ√©e"

[preprocessor.playscript]
command = "../../target/debug/mdbook-playscript"
subtitle = "Le Mariage de Figaro"

[output.html]
additional-css = ["mdplayscript.css"]
